-- insert entrega
INSERT INTO ENTREGAS (ENTREGA_ID, VIAGEM_ID, CLIENTE_ID, ENDERECO_ENTREGA, STATUS)
VALUES (1, 1, 1, 'Fortaleza Ceara', 'Concluído');
SELECT * FROM ENTREGAS;


-- insert cliente
INSERT INTO CLIENTES (CLIENTE_ID, NOME, TELEFONE, EMAIL, ENDERECO)
VALUES (1, 'João Pedro', '(11) 99999-7777', 'joao.pedro@email.com', 'Rua B, 456');
SELECT * FROM CLIENTES;


-- insert viagens
INSERT INTO VIAGENS (VIAGEM_ID, VEICULO_ID, MOTORISTA_ID, ROTA_ID, DATA_PARTIDA, DATA_CHEGADA, STATUS)
VALUES (1, 1, 1, 1, TO_DATE('2024-12-03', 'YYYY-MM-DD'), TO_DATE('2024-12-06', 'YYYY-MM-DD'), 'Concluída');
SELECT * FROM VIAGENS;


-- insert motoristas
INSERT INTO MOTORISTAS (MOTORISTA_ID, NOME, CNH, TELEFONE)
VALUES (1, 'Sebastião Cardoso', '60641966269', '(11) 92830-4957');
SELECT * FROM motoristas;


-- insert rotas
INSERT INTO ROTAS (ROTA_ID, ORIGEM, DESTINO, DISTANCIA)
VALUES (1, 'Xique_Xique Bahia', 'Fortaleza Ceara', 1231);
SELECT * FROM rotas;


-- insert veiculos
INSERT INTO VEICULOS (VEICULO_ID, PLACA, MODELO, CAPACIDADE_CARGA, STATUS)
VALUES (1, 'LVH-5796', 'Legend 3.2/3.5', 1000, 'disponível');